"""
Base Agent — shared logic for all Sub-Agents.
Wraps Anthropic SDK with structured output tool-use.
Supports mock mode (no API key needed) by calling data tools directly.
"""
import json
import os
from typing import Any, Callable
try:
    from anthropic import Anthropic
except ImportError:
    Anthropic = None  # graceful fallback when package not installed

TOOLS_REGISTRY: dict[str, Callable] = {}

def register_tool(fn: Callable):
    """Decorator to register a tool for Claude function-calling."""
    TOOLS_REGISTRY[fn.__name__] = fn
    return fn


def has_api_key() -> bool:
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    return bool(key) and not key.startswith("sk-ant-xxx")


class BaseAgent:
    """Every Sub-Agent extends BaseAgent."""

    def __init__(self, name: str, system_prompt: str, model: str = "claude-sonnet-4-20250514"):
        self.name = name
        self.system_prompt = system_prompt
        self.model = model
        self.use_mock = not has_api_key() or Anthropic is None

    def get_tool_defs(self) -> list[dict]:
        """Override to return Claude tool definitions for this agent."""
        return []

    def execute_tool(self, tool_name: str, args: dict) -> Any:
        """Run a registered tool by name."""
        fn = TOOLS_REGISTRY.get(tool_name)
        if fn:
            return fn(**args)
        raise ValueError(f"Unknown tool: {tool_name}")

    def _build_messages(self, input_text: str, context: list[dict] | None = None) -> list[dict]:
        msgs = []
        if context:
            msgs.extend(context)
        msgs.append({"role": "user", "content": input_text})
        return msgs

    def run(self, input_text: str, output_schema: dict | None = None, context: list[dict] | None = None) -> dict | str:
        """
        Run the agent with optional structured output.
        If no API key, runs in mock mode — calls data tools directly.
        """
        if self.use_mock:
            return self._run_mock(input_text, output_schema)

        # Real Claude API call
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        client = Anthropic(api_key=api_key)

        tools = self.get_tool_defs()
        extra_kwargs = {}

        if output_schema:
            tools.append({
                "name": output_schema["name"],
                "description": f"Structured output for {self.name}",
                "input_schema": output_schema["schema"],
            })
            # Use "any" tool_choice to avoid thinking-mode conflicts
            extra_kwargs["tool_choice"] = {"type": "any"}

        msgs = self._build_messages(input_text, context)

        response = client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=self.system_prompt,
            messages=msgs,
            tools=tools if tools else None,
            **extra_kwargs,
        )

        for block in response.content:
            if block.type == "tool_use":
                # Check if it matches the output schema name
                if output_schema and block.name == output_schema["name"]:
                    return block.input
                # Otherwise it's a data tool — execute it
                result = self.execute_tool(block.name, block.input)
                if not output_schema:
                    return result
                # If output_schema expected but this was a tool call, continue
                # Actually for mock mode, we don't reach here often
                continue

        # Fallback: text response
        return response.content[0].text if response.content else ""

    def _run_mock(self, input_text: str, output_schema: dict | None = None) -> dict | str:
        """Mock mode: directly return structured data without calling Claude.
        Each Sub-Agent overrides this to provide domain-appropriate mock data.
        """
        if output_schema:
            return self._generate_mock_output(input_text, output_schema)
        return {"message": f"[{self.name}] Mock response for: {input_text[:80]}..."}

    def _generate_mock_output(self, input_text: str, schema: dict) -> dict:
        """Override in each Sub-Agent to return realistic mock data."""
        return {"mock": True, "note": f"Generated by {self.name} in mock mode"}
